apiVersion: apps/v1
kind: Deployment
metadata:
  name: realworld-nginx
spec:
  selector:
    matchLabels:
      app: realworld-nginx
  template:
    metadata:
      labels:
        app: realworld-nginx
    spec:
      containers:
      - name: realworld
        image: sheriffexcel/realworld-nginx
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: realworld-nginx-svc
spec:
  type: LoadBalancer
  selector:
    app: realworld-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80