apiVersion: apps/v1
kind: Deployment
metadata:
  name: realworld-deploy
spec:
  selector:
    matchLabels:
      app: realworld
  template:
    metadata:
      labels:
        app: realworld
    spec:
      containers:
      - name: realworld
        image: sheriffexcel/realworld-nginx
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: realworld
spec:
  type: LoadBalancer
  selector:
    app: realworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80