apiVersion: apps/v1
kind: Deployment
metadata:
  name: realworld-deploy
spec:
  selector:
    matchLabels:
      app: realworld
  template:
    metadata:
      labels:
        app: realworld
    spec:
      containers:
      - name: realworld
        image: sheriffexcel/realworld-app
        tty: true
        command: ["/bin/sh", "-c"]
        args: ["python manage.py makemigrations &&
            python manage.py migrate &&
            gunicorn realworld.wsgi:application --bind 0.0.0.0:8000"]
        ports:
        - containerPort: 8000
        
        env:
        - name: DB_NAME
          value: "postgresdb"

        - name: DB_PASSWORD
          # value: "admin"
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD

        - name: DB_HOST
          value: "postgres"

        - name: DB_PORT
          value: "5432"
          
        - name: DB_USER
          value: "admin"

---

apiVersion: v1
kind: Service
metadata:
  name: realworld
spec:
  selector:
    app: realworld
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000